### PR TITLE
Add npm package.json

### PR DESCRIPTION
**Pull request by ds-hwang**
It makes newcomer's life easier.
- Install npm packages
  
  > npm install
- Build index.html
  
  > node build.js

### CODE REVIEW

**Comment by anssiko** [comment]
@ds-hwang Travis CI failed. I merged this regardless of the failure, since you're in the group, but Travis CI did not just know about it. Here's how to fix:

Go to https://www.w3.org/users/myprofile and add your GitHub account to Links like this:

Link: https://github.com/ds-hwang
Label: GitHub

Also in https://github.com/settings/profile change Company to the full name "Intel Corporation".

This will associate your GH account with your W3C account and your PRs will pass the Travis CI the next time.

**Comment by dontcallmedom** [comment]
@anssiko actually, that's not how this works; I needed to add @ds-hwang to the repo manager, which I have now done, which means future PR shouldn't be an issue.

Please ping me if/when this happens again (making myself pinged automatically is part of the [suggested improvements to the repo manager](https://github.com/w3c/ash-nazg/issues/27) :)

**Comment by ds-hwang** [comment]
@dontcallmedom thx for quick action!

@anssiko thx for detail explaining. 
My w3 profile already points out my github. https://www.w3.org/users/76134
I changed github profile Company to the full name "Intel Corporation".

**Comment by ds-hwang** [comment]
@dontcallmedom My next PR #130 passed!! :+1:

**Comment by anssiko** [comment]
Thanks @dontcallmedom! https://github.com/w3c/ash-nazg/ has always been a bit of mystery to me -- good to know who to bug when this occurs :-)

**Comment by anssiko** [comment]
@dontcallmedom Could you also check that @bbernhar is in the repo manager for this spec?

I also noticed neither @ds-hwang nor @bbernhar have that precious "World Wide Web Consortium member" badge beside their GH comments. Is this related, how to fix?

Both are formal DAS WG participants.

**Comment by dontcallmedom** [comment]
@anssiko I have added @bbernhar to the repo manager.

The "W3C member" badge in github comes from having been invited to join a repo from the organization; I've just sent them the invitations.

**Comment by anssiko** [comment]
Thanks! I thought all the WG participants would get the W3C badge automatically, and thought it could be used as a visual indicator if a person is a formal WG participant. That would actually be a rather nice feature, i.e. be able to know if the comment was made by a formal WG participant without needing to manually check dbwg. Now we only get that type of treatment for PRs via Travis CI ipr check (which is great advancement from what it used to be!).

But thinking about this more, I can guess automating that would not be straight-forward, if even possible with the current GitHub API. Feel free to open an issue against an appropriate W3C tool if you feel that would be a reasonable feature request.

**Pull request merged**
