### PR TITLE
small improvement of 2D canvas example

### PR DESCRIPTION
**Pull request by ds-hwang**

### CODE REVIEW

**Comment by ds-hwang** [comment]
@anssiko @huningxin could you review?

**Comment by anssiko** [comment]
@ds-hwang LGTM. Thanks for fixing the bug in the example and modernising it by means of using rAF.

**Comment by ds-hwang** [comment]
thx for quick reviewing :)

**Comment by huningxin** [comment]
@ds-hwang , LGTM! Thanks for the fixing!

**Pull request merged**
